Repository EGI-Federation/cloud-info-provider, pull requests merged in 2019-02, with the labels that each got.

#145 Document appdb update
  RELEASING.md
Labels: :blue_book: documentation, enhancement

#148 RELEASING: documnent pushing packages to CMD
  RELEASING.md
Labels: :blue_book: docs

#151 Fix network info
  cloud_info_provider/providers/opennebula.py
  cloud_info_provider/providers/openstack.py
  cloud_info_provider/utils.py
  etc/templates/compute.glue21
Labels: bug

#152 Add missing CMDB compute template
  etc/templates/compute.cmdb.json
Labels: enhancement
